SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `synapse`.`location` CHANGE COLUMN `typeLocation` `typeLocation` ENUM('CITY','STATE','COUNTRY') NOT NULL DEFAULT 'CITY'  , CHANGE COLUMN `name` `name` VARCHAR(60) NOT NULL  , CHANGE COLUMN `acronym` `acronym` VARCHAR(30) NULL DEFAULT NULL  ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
